spring:
    application:
        name: ResumeBack

    datasource:
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/symmetry
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}


    jpa:
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true

                dialect: org.hibernate.dialect.PostgreSQLDialect

        hibernate:
            ddl-auto: update
        generate-ddl: true
        show-sql: true


    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties: 
            mail: 
                smtp:
                    auth: true

                    starttls:
                        enable: true


server:
    port: 8080

app:
    filesPath: ${FILES_PATH}
    corprequests:
        address: ${MAIL_CORPREQADDRESS}



sha:
    key: d66c86fc243cf2f051e48cfb12ddbefb357b618f062c9049bc48c598fcf432e0

jwt:
    secret:
        access: WO+xvwq2FDpNkMAWoJZXbXeHMcgAqO/5aNiDEBJ2aus=
        refresh: WO+xvwq2FDpNkMAWoJZXbXeHMcgAqO/5aNiDEBJ2aus=

expiration-time:
    refresh:
        day: 1
        hour: 1
        minute: 1
        second: 1

    access:
        day: 1
        hour: 1
        minute: 1
        second: 1